### ISSUE TITLE
Error using the Avatar Menu

### ISSUE THREAD

**Issue by DaveHOnCode** [yagizhanNY/siemens-ix-blazor#6]
If I use the `NavigationMenuAvatar`, an error comes up:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'addEventListener')
      TypeError: Cannot read properties of null (reading 'addEventListener')
          at Module.listenEvent (https://localhost:7208/_content/SiemensIXBlazor/js/interops/baseJsInterop.js:3:13)
          at https://localhost:7208/_framework/blazor.webassembly.js:1:3337
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:7208/_framework/blazor.webassembly.js:1:3311)
          at Object.Gt [as invokeJSFromDotNet] (https://localhost:7208/_framework/blazor.webassembly.js:1:62569)
          at Object.Ii (https://localhost:7208/_framework/dotnet.7.0.5.eqs19pya6r.js:5:71974)
          at _mono_wasm_invoke_js_blazor (https://localhost:7208/_framework/dotnet.7.0.5.eqs19pya6r.js:14:103886)
          at wasm://wasm/00992dae:wasm-function[313]:0x1d507
          at wasm://wasm/00992dae:wasm-function[283]:0x1c935
          at wasm://wasm/00992dae:wasm-function[221]:0xe025
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'addEventListener')
TypeError: Cannot read properties of null (reading 'addEventListener')
    at Module.listenEvent (https://localhost:7208/_content/SiemensIXBlazor/js/interops/baseJsInterop.js:3:13)
    at https://localhost:7208/_framework/blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:7208/_framework/blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:7208/_framework/blazor.webassembly.js:1:62569)
    at Object.Ii (https://localhost:7208/_framework/dotnet.7.0.5.eqs19pya6r.js:5:71974)
    at _mono_wasm_invoke_js_blazor (https://localhost:7208/_framework/dotnet.7.0.5.eqs19pya6r.js:14:103886)
    at wasm://wasm/00992dae:wasm-function[313]:0x1d507
    at wasm://wasm/00992dae:wasm-function[283]:0x1c935
    at wasm://wasm/00992dae:wasm-function[221]:0xe025
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at SiemensIXBlazor.Interops.BaseInterop.AddEventListener(Object classObject, String id, String eventName, String callbackFunctionName)
   at SiemensIXBlazor.Components.NavigationMenu.NavigationMenuAvatar.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by yagizhanNY** [comment]
Hi @DaveHOnCode, could you also add how you are using this component in razor page?

**Comment by DaveHOnCode** [comment]
```
 <BasicNavigation ApplicationName="Application name">
        <placeholder-logo slot="logo"></placeholder-logo>
        <NavigationMenu Id="nav-menu-1">
        <NavigationMenuAvatar initials="AA">
            <NavigationMenuAvatarItem Label="Option 1"></NavigationMenuAvatarItem>
        </NavigationMenuAvatar>
            <NavLink href="" Match="NavLinkMatch.All" ><NavigationMenuItem TabIcon="home" Home="true">Home</NavigationMenuItem></NavLink>
            <NavLink href="DataGridPage"><NavigationMenuItem TabIcon="table">Table</NavigationMenuItem></NavLink>
        </NavigationMenu>
         <article class="content p-3"> 
             @Body 
         </article> 
    </BasicNavigation>
```

**Comment by yagizhanNY** [comment]
```html
<BasicNavigation ApplicationName="Application name">
        <placeholder-logo slot="logo"></placeholder-logo>
        <NavigationMenu Id="nav-menu-1">
        <NavigationMenuAvatar Id="nav-menu-avatar-1" Initials="AA">
            <NavigationMenuAvatarItem Label="Option 1"></NavigationMenuAvatarItem>
        </NavigationMenuAvatar>
            <NavLink href="" Match="NavLinkMatch.All" ><NavigationMenuItem TabIcon="home" Home="true">Home</NavigationMenuItem></NavLink>
            <NavLink href="DataGridPage"><NavigationMenuItem TabIcon="table">Table</NavigationMenuItem></NavLink>
        </NavigationMenu>
         <article class="content p-3"> 
             @Body 
         </article> 
    </BasicNavigation>
```

You must also add `Id` attribute to the `NavigationMenuAvatar` component. Also you should change `initilas` to `Initials`.

Please let me know if it's worked.

**Comment by DaveHOnCode** [comment]
No it still does not work

**Comment by yagizhanNY** [comment]
```html
<BasicNavigation ApplicationName="Application name">
        <placeholder-logo slot="logo"></placeholder-logo>
        <NavigationMenu Id="nav-menu-1">
        <NavigationMenuAvatar Id="nav-menu-avatar-1" Initials="AA">
            <NavigationMenuAvatarItem Id="avatar-item" Label="Option 1"></NavigationMenuAvatarItem>
        </NavigationMenuAvatar>
            <NavLink href="" Match="NavLinkMatch.All" ><NavigationMenuItem TabIcon="home" Home="true">Home</NavigationMenuItem></NavLink>
            <NavLink href="DataGridPage"><NavigationMenuItem TabIcon="table">Table</NavigationMenuItem></NavLink>
        </NavigationMenu>
         <article class="content p-3"> 
             @Body
         </article> 
</BasicNavigation>
```

You must add `Id` attribute to the `NavigationMenuAvatarItem` too. 

![image](https://github.com/yagizhanNY/siemens-ix-blazor/assets/41087670/444eb272-b997-44d3-b869-0fe8af51d4c4)

In Visual Studio, you can see the warning about `Id` attribute.

**Comment by DaveHOnCode** [comment]
Ahh okay thanks, that was the solution

I'm currently not using Visual Studio

**Comment by DaveHOnCode** [comment]
But it would be nice to put this in the documentation, its currently not there...
