### ISSUE TITLE
DateTimePicker weird colors, Error on Done Event

### ISSUE THREAD

**Issue by DaveHOnCode** [yagizhanNY/siemens-ix-blazor#8]
I think the picture is self explanatory: 

![image](https://github.com/yagizhanNY/siemens-ix-blazor/assets/32842330/951fad8b-9e06-4856-91eb-e9297c3f2fd9)

While using the Done Event with the code:

`DoneEvent="s => Console.WriteLine(s)"`

the following Error appears:

```
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, String& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
```

And why do I have to provide the From and To Dates?

Thank you so much in advance!

**Comment by yagizhanNY** [comment]
Style is looks fine on my browser. If you are using additional css library or custom css on this page, this could be the problem. Check please.

I have added new return object `DateTimePickerResponse` to this component. `DateSelectEvent` will start to return `DateTimePickerResponse` object in new release.

**Comment by DaveHOnCode** [comment]
Wouldn't it make sense to return a DateTime or DateOnly / TimeOnly Object instead of strings?

**Comment by yagizhanNY** [comment]
It could be but in siemens ix library it's returning as;

```json
{
     "from": "xxxx",
     "to": "xxxxx",
     "time": "xxxxx"
}
```

Because of that, I want to return same object type in our library.
